### ISSUE TITLE
backword compatibility 

### ISSUE THREAD

**Issue by lb-ronyeh** [tlsfuzzer/tlslite-ng#487]
hi, using tlslite-ng==0.7.6

i Replaced old  pycrypto with pycryptodome (the replacement should be drop in)

but tslite is using some old Cipher maybe ?

when tested with suggested package there was an exception when trying to authorize

```
Traceback (most recent call last):
File "oauth_authorization_tool.py", line 155, in
private_key_file)
File "oauth_authorization_tool.py", line 59, in request_oauth_token
resp, content = client.request(request_token_url, "POST")
File "/usr/local/lib/python3.7/site-packages/oauth2/init.py", line 673, in request
req.sign_request(self.method, self.consumer, self.token)
File "/usr/local/lib/python3.7/site-packages/oauth2/init.py", line 502, in sign_request
self['oauth_signature'] = signature_method.sign(self, consumer, token)
File "/home/xxxx/xxxx/utils/signature_method.py", line 35, in sign
signature = privatekey.hashAndSign(raw)
File "/usr/local/lib/python3.7/site-packages/tlslite/utils/rsakey.py", line 82, in hashAndSign
saltLen=sLen)
File "/usr/local/lib/python3.7/site-packages/tlslite/utils/rsakey.py", line 320, in sign
sigBytes = self._raw_pkcs1_sign(bytes)
File "/usr/local/lib/python3.7/site-packages/tlslite/utils/rsakey.py", line 287, in _raw_pkcs1_sign
c = self._rawPrivateKeyOp(m)
File "/usr/local/lib/python3.7/site-packages/tlslite/utils/pycrypto_rsakey.py", line 32, in _rawPrivateKeyOp
c = self.rsa.decrypt((m,))
File "/usr/local/lib/python3.7/site-packages/Crypto/PublicKey/RSA.py", line 382, in decrypt
raise NotImplementedError("Use module Crypto.Cipher.PKCS1_OAEP instead")
NotImplementedError: Use module Crypto.Cipher.PKCS1_OAEP instead
```

**Comment by tomato42** [comment]
pycryptodome is not a drop-in replacement for pycrypto

duplicate of #198
